-- Standard v21 / Batch 6A
-- Seed default rows into public.payment_methods so the seller dashboard's
-- payment verification dropdown has options to choose from.
--
-- Notes:
--   - Migration 001 already includes the same seed at the bottom of the file.
--     This migration is purposely redundant: it lets fresh / partial /
--     replicated environments converge on the same canonical list without
--     requiring an out-of-repo SQL snippet.
--   - on conflict (slug) do nothing keeps this idempotent and re-runnable.
--   - To add or rename a payment method later, create a new migration
--     (004_..., 005_...). Do not edit this file or 001_initial_schema.sql.

insert into public.payment_methods (name, slug) values
  ('Crypto', 'crypto'),
  ('PayPal G&S', 'paypal-gs'),
  ('PayPal F&F', 'paypal-ff'),
  ('Card', 'card'),
  ('CashApp', 'cashapp'),
  ('Skrill', 'skrill'),
  ('Wise', 'wise'),
  ('Gift Cards', 'gift-cards'),
  ('Bank Transfer', 'bank-transfer')
on conflict (slug) do nothing;
